export const vuetifyTheme = {
    defaultTheme: 'light',
    themes: {
        light: {
            dark: false,
            colors: {
                background: '#FAFAF8',
                'on-background': '#292824',
                surface: '#FFFFFF',
                'on-surface': '#292824',
                'surface-bright': '#FFFFFF',
                'surface-light': '#EEEEEE',
                'surface-dark': '#E0E0E0',
                'surface-variant': '#424242',
                'on-surface-variant': '#EEEEEE',
                primary: '#1867C0',
                'primary-darken-1': '#1F5592',
                secondary: '#48A9A6',
                'secondary-darken-1': '#018786',
                error: '#B00020',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FB8C00',
                'nav-background': '#EBEBE7',
                'on-nav-background': '#292824',
            },
            variables: {
                'border-opacity': 0.08,
                'activated-opacity': 0.06,
            },
        },
        dark: {
            dark: true,
            colors: {
                background: '#121212',
                surface: '#212121',
                'surface-bright': '#ccbfd6',
                'surface-light': '#424242',
                'surface-dark': '#343434',
                'surface-variant': '#c8c8c8',
                'on-surface-variant': '#000000',
                primary: '#2196f3',
                'primary-darken-1': '#277CC1',
                secondary: '#54B6B2',
                'secondary-darken-1': '#48A9A6',
                error: '#CF6679',
                info: '#2196F3',
                success: '#4CAF50',
                warning: '#FB8C00',
                'nav-background': '#212121',
            },
        },
    },
};
